version: "3.3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password_root"
      MYSQL_DATABASE: "django_docker_v0"
    volumes:
      - /var/lib/mysql

  web:
    build: .
    environment:
      - DEBUG=True
      - DB_NAME=django_docker_v0
      - DB_USER=root
      - DB_PASSWORD=password_root
      - DB_HOST=localhost
    ports:
      - "8000:8000"